### ISSUE TITLE
Ignore generated files from sizing?

### ISSUE THREAD

**Issue by petemounce** [boschresearch/pr-size-labeler#10]
We use `.gitattributes` like 

```
foo.something.file linguist-generated
```

to denote generated code [a la github's linguist docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github).

Any chance the sizing calculation could (conditionally on config) discount those files?

**Comment by realJohnDoe** [comment]
Hi @petemounce,

first of all, thanks for the feature request. We appreciate that you tried out our action and think about how it could be improved.

Unfortunately, adding an ignore-option would both require some reimplementation and maintenance of [how we currently calculate the diff size](https://github.com/boschresearch/pr-size-labeler/blob/main/index.js#L31) as well as violate our main design rule of keeping this action as simple as possible and follow GitHub's default wherever possible. I will thus close this issue.

**Comment by petemounce** [comment]
Thanks for responding.
