### ISSUE TITLE
Exclusion of files

### ISSUE THREAD

**Issue by ekosman** [boschresearch/pr-size-labeler#3]
Sometimes I commit files with a lot of changes that shouldn't be reviewed, such as `poetry.lock`. Is it possible to exclude specific files?

**Comment by realJohnDoe** [comment]
Hi @ekosman,
thanks for bringing up that suggestion! 
One design decision we made for this action is to simply use the diff numbers as shown in GitHub to calculate a size and comment. We think this makes it very transparent for the users why a certain label is chosen.
Your suggestion would break with this idea to some degree. I would rather suggest to run the action in a small workflow and use [GitHubs `path` or `path_ignore`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to prevent the workflow from running when certain automatically generated files are pushed.
What do you think?
